<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN' 'http://www.w3.org/TR/html4/loose.dtd'>
<html>
<head>
<!-- SchemaSpy rev ${globalData.schemaspyRevision} -->
<title>SchemaSpy - ${descriptionHeader}</title>
<link rel=stylesheet href='/schemaSpy.css' type='text/css'>
<meta HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=${globalData.config.charset}'>
<SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='/jquery.js'></SCRIPT>
<SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='/schemaSpy.js'></SCRIPT>
<SCRIPT LANGUAGE='JavaScript' TYPE='text/javascript' SRC='/jquery.tablesorter.js'></SCRIPT>
</head>
<body>
<table id='headerHolder' cellspacing='0' cellpadding='0'><tr><td>
<div id='header'>
 <ul>
<#if globalData.config.oneOfMultipleSchemas>
      <li><a href='/index.html' title='All Schemas Evaluated'>Schemas</a></li>
</#if>
  <li <#if 'index' == currentPageName>id='current'</#if>><a href='index.html' title='All tables and views in the schema'>Tables</a></li>
  <li <#if 'relationships' == currentPageName>id='current'</#if>><a href='relationships.html' title='Diagram of table relationships'>Relationships</a></li>
<#if globalData.config.hasOrphans()>
      <li <#if 'utilities' == currentPageName>id='current'</#if>><a href='utilities.html' title='View of tables with neither parents nor children'>Utility&nbsp;Tables</a></li>
</#if>
  <li <#if 'constraints' == currentPageName>id='current'</#if>><a href='constraints.html' title='Useful for diagnosing error messages that just give constraint name or number'>Constraints</a></li>
  <li <#if 'anomalies' == currentPageName>id='current'</#if>><a href='anomalies.html' title="Things that might not be quite right">Anomalies</a></li>
  <li <#if 'columns' == currentPageName>id='current'</#if>><a href='columns.byColumns.html' title="All of the columns in the schema">Columns</a></li>
<#if globalData.config.hasRoutines()>
      <li <#if 'routines' == currentPageName>id='current'</#if>><a href='routines.html' title='Stored Procedures / Functions'>Routines</a></li>
</#if>
  <li><a href='http://sourceforge.net/donate/index.php?group_id=137197' title='Please help keep SchemaSpy alive' target='_blank'>Donate</a></li>
 </ul>
</div>
</td>
</tr>
</table>

<div class='content' style='clear:both;'>
<table width='100%' border='0' cellpadding='0'>
    <tr>
        <td class='heading' valign='middle'>
        <span class='header'>
        <#if !table?has_content>SchemaSpy Analysis of</#if>
        ${descriptionContent}
        </span>
        <#if !table?has_content && globalData.database.description?has_content><span class='description'>${globalData.database.description}</span></#if>
         <#if table?has_content && table.comments?has_content>
         	<div style='padding: 0px 4px;'>
         	${table.comments}
         	</div>
         </#if>    
</td>
 <td class='heading' align='right' valign='top' title='John Currier - Creator of Cool Tools'><span class='indent'>Generated by</span><br><span class='indent'><span class='signature'><a href='http://schemaspy.sourceforge.net' target='_blank'>SchemaSpy</a></span></span></td>
 </tr>
</table>        